//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/msg/CTS.msg.
//

#ifndef __CTS_M_H
#define __CTS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CTS;
/**
 * Class generated from <tt>src/msg/CTS.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CTS
 * {
 *     string cts_name;
 *     string rts_name;
 *     int rts_id;
 * 
 *     int cts_srcID;//CTS的发送者是server
 *     int cts_destID;//CTS的接收者&&data发送者&&RTS发送者data
 *     int cts_dataID;//sensor根据ID判断是不是重发。
 *     //double cts_TxTime;
 *     simtime_t cts_TxTime;//server给sensor安排的发送时间。
 * 
 *     double cts_DataTxDelay1;//server给sensor安排的发送传输延迟
 *     double cts_DataTxDelay2;//server给sensor安排的发送传播延迟
 * 
 *     double cts_TxChannel;//server给sensor安排的信道。
 *     double cts_TxPower;//server给sensor安排的功率。
 *     double cts_TxDirection;//server给sensor安排的方向。
 *     double cts_transportationDelay;//cts的传输延迟
 * }
 * </pre>
 */
class CTS : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string cts_name;
    omnetpp::opp_string rts_name;
    int rts_id = 0;
    int cts_srcID = 0;
    int cts_destID = 0;
    int cts_dataID = 0;
    omnetpp::simtime_t cts_TxTime = SIMTIME_ZERO;
    double cts_DataTxDelay1 = 0;
    double cts_DataTxDelay2 = 0;
    double cts_TxChannel = 0;
    double cts_TxPower = 0;
    double cts_TxDirection = 0;
    double cts_transportationDelay = 0;

  private:
    void copy(const CTS& other);

  protected:
    bool operator==(const CTS&) = delete;

  public:
    CTS(const char *name=nullptr, short kind=0);
    CTS(const CTS& other);
    virtual ~CTS();
    CTS& operator=(const CTS& other);
    virtual CTS *dup() const override {return new CTS(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getCts_name() const;
    virtual void setCts_name(const char * cts_name);

    virtual const char * getRts_name() const;
    virtual void setRts_name(const char * rts_name);

    virtual int getRts_id() const;
    virtual void setRts_id(int rts_id);

    virtual int getCts_srcID() const;
    virtual void setCts_srcID(int cts_srcID);

    virtual int getCts_destID() const;
    virtual void setCts_destID(int cts_destID);

    virtual int getCts_dataID() const;
    virtual void setCts_dataID(int cts_dataID);

    virtual omnetpp::simtime_t getCts_TxTime() const;
    virtual void setCts_TxTime(omnetpp::simtime_t cts_TxTime);

    virtual double getCts_DataTxDelay1() const;
    virtual void setCts_DataTxDelay1(double cts_DataTxDelay1);

    virtual double getCts_DataTxDelay2() const;
    virtual void setCts_DataTxDelay2(double cts_DataTxDelay2);

    virtual double getCts_TxChannel() const;
    virtual void setCts_TxChannel(double cts_TxChannel);

    virtual double getCts_TxPower() const;
    virtual void setCts_TxPower(double cts_TxPower);

    virtual double getCts_TxDirection() const;
    virtual void setCts_TxDirection(double cts_TxDirection);

    virtual double getCts_transportationDelay() const;
    virtual void setCts_transportationDelay(double cts_transportationDelay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CTS& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CTS& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CTS *fromAnyPtr(any_ptr ptr) { return check_and_cast<CTS*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CTS_M_H

