//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/msg/Data.msg.
//

#ifndef __DATA_M_H
#define __DATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Data;
/**
 * Class generated from <tt>src/msg/Data.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Data
 * {
 *     string data_name;
 *     int data_id;
 *     int data_srcId;
 *     int data_destId;
 *     double data_sendPower;
 *     double data_sendFrequency;
 *     double data_dataLenBit;
 *     simtime_t sendingTime;
 * 
 * 
 * }
 * </pre>
 */
class Data : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string data_name;
    int data_id = 0;
    int data_srcId = 0;
    int data_destId = 0;
    double data_sendPower = 0;
    double data_sendFrequency = 0;
    double data_dataLenBit = 0;
    omnetpp::simtime_t sendingTime = SIMTIME_ZERO;

  private:
    void copy(const Data& other);

  protected:
    bool operator==(const Data&) = delete;

  public:
    Data(const char *name=nullptr, short kind=0);
    Data(const Data& other);
    virtual ~Data();
    Data& operator=(const Data& other);
    virtual Data *dup() const override {return new Data(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData_name() const;
    virtual void setData_name(const char * data_name);

    virtual int getData_id() const;
    virtual void setData_id(int data_id);

    virtual int getData_srcId() const;
    virtual void setData_srcId(int data_srcId);

    virtual int getData_destId() const;
    virtual void setData_destId(int data_destId);

    virtual double getData_sendPower() const;
    virtual void setData_sendPower(double data_sendPower);

    virtual double getData_sendFrequency() const;
    virtual void setData_sendFrequency(double data_sendFrequency);

    virtual double getData_dataLenBit() const;
    virtual void setData_dataLenBit(double data_dataLenBit);

    virtual omnetpp::simtime_t getSendingTime() const;
    virtual void setSendingTime(omnetpp::simtime_t sendingTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Data& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Data& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Data *fromAnyPtr(any_ptr ptr) { return check_and_cast<Data*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATA_M_H

