//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/msg/RTS.msg.
//

#ifndef __RTS_M_H
#define __RTS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RTS;
/**
 * Class generated from <tt>src/msg/RTS.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet RTS
 * {
 *     string rts_name;
 *     bool rts_isReceived = false;//是否收到data
 *     int rts_receivedID;//收到的谁发的data，，server以此来判断是否重发data或者删除缓存中的data信息。
 *     bool rts_isTransmit = false;//是否有data要发送：若是,则继续读取后面的消息;若否，则停止接收后续信息。
 *     int rts_srcID;//data发送者&&RTS发送者
 *     int rts_dataDestID;//data接收者，RTS的接收者永远是Server
 *     int rts_dataID;
 *     int rts_dataLenBit;//data长度
 *     bool rts_state;//状态（是否被读取）
 *     double rts_sendPower;//rts的发送能量
 * 
 * 
 * 
 * }
 * </pre>
 */
class RTS : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string rts_name;
    bool rts_isReceived = false;
    int rts_receivedID = 0;
    bool rts_isTransmit = false;
    int rts_srcID = 0;
    int rts_dataDestID = 0;
    int rts_dataID = 0;
    int rts_dataLenBit = 0;
    bool rts_state = false;
    double rts_sendPower = 0;

  private:
    void copy(const RTS& other);

  protected:
    bool operator==(const RTS&) = delete;

  public:
    RTS(const char *name=nullptr, short kind=0);
    RTS(const RTS& other);
    virtual ~RTS();
    RTS& operator=(const RTS& other);
    virtual RTS *dup() const override {return new RTS(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRts_name() const;
    virtual void setRts_name(const char * rts_name);

    virtual bool getRts_isReceived() const;
    virtual void setRts_isReceived(bool rts_isReceived);

    virtual int getRts_receivedID() const;
    virtual void setRts_receivedID(int rts_receivedID);

    virtual bool getRts_isTransmit() const;
    virtual void setRts_isTransmit(bool rts_isTransmit);

    virtual int getRts_srcID() const;
    virtual void setRts_srcID(int rts_srcID);

    virtual int getRts_dataDestID() const;
    virtual void setRts_dataDestID(int rts_dataDestID);

    virtual int getRts_dataID() const;
    virtual void setRts_dataID(int rts_dataID);

    virtual int getRts_dataLenBit() const;
    virtual void setRts_dataLenBit(int rts_dataLenBit);

    virtual bool getRts_state() const;
    virtual void setRts_state(bool rts_state);

    virtual double getRts_sendPower() const;
    virtual void setRts_sendPower(double rts_sendPower);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RTS& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RTS& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RTS *fromAnyPtr(any_ptr ptr) { return check_and_cast<RTS*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RTS_M_H

